### PR TITLE
Delete ChangeLog.md

### PR DESCRIPTION
**Pull request by keradus**
Changelog is confusing only, it mention only one release, while there are few more.

### CODE REVIEW

**Comment by julienfalque** [comment]
I would make it up-to-date rather than removing it.

**Comment by keradus** [comment]
that's the thing, nobody cares, either we, as ppl who release it, or users, as ppl who may want to have it. so why bother and spent time on it ?
(other thing, is that this package was release as internal one and is supposed to be used only by PHP CS Fixer v2 (v3 is already not using fork anymore)

**Review by julienfalque — APPROVED** [review]
> (other thing, is that this package was release as internal one and is supposed to be used only by PHP CS Fixer v2 (v3 is already not using fork anymore)

Forgot that point, :+1: for removal

**Comment by SpacePossum** [comment]
thanks @keradus , indeed nice to clean up to prevent confusion :+1:

**Pull request merged**
