### PR TITLE
Add PHP 8.0 runtime support

### PR DESCRIPTION
**Pull request by mvorisek**
must target 1.x (and 2.x)

related with https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5034

release 1.x must be then tagged/released

### CODE REVIEW

**Comment by mvorisek** [comment]
@SpacePossum LGTM?

**Comment by kubawerlos** [comment]
This is definitely no-go, how do you ensure it works on PHP 8?

At very least PHP 8 build should have `--ignore-platform-reqs` removed and be not allowed to fail.

**Comment by mvorisek** [comment]
@kubawerlos run phpunit tests locally using php8, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5034#issuecomment-652646416 why CS fixer should be installable on php8 without extra config needed

**Comment by kubawerlos** [comment]
I don't want to need to run it locally, that's what CI is for.

**Comment by mvorisek** [comment]
> 
> 
> I don't want to need to run it locally, that's what CI is for.

I analysed the Travis CI and it is tested with `nighty` php build, thus php8 already.

**Comment by kubawerlos** [comment]
Yes, it is tested with `--ignore-platform-reqs` and is allowed to fail, that's what I was referring in https://github.com/PHP-CS-Fixer/diff/pull/18#issuecomment-652638798.

**Comment by mvorisek** [comment]
I know, I reviewed it, but dev requirement to tests this PR are not php8 installable (should be fixed with phpunit release on Aug 7, 2020 - do we need to wait until then?)

**Comment by SpacePossum** [comment]
Putting PHP8 in composer suggest we support it, we've tested it and are confident the tool will work fine on it. 
Looking at PHP8 [timetable](https://wiki.php.net/todo/php80) the official release is at Nov 26, with a lot of RC's before it. As such I would not claim we support it as of yet. It would be great to start and continue testing on the RC's, but for now it is just to early IMHO.

**Comment by SpacePossum** [comment]
Closing for now to keep focus on bugs and more pressing issues, please comment when PHP 8 RC is out than I'll reopen! :)

**Pull request closed without merging**
